version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://pulse_user:pulse_password@db:5432/pulse_db
      - NODE_ENV=production
    depends_on:
      - db
    restart: always
    volumes:
      - ./public:/app/public
      - ./src/data:/app/src/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pulse-app.rule=Host(`pulse3d.ru`) || Host(`www.pulse3d.ru`)"
      - "traefik.http.routers.pulse-app.entrypoints=websecure"
      - "traefik.http.routers.pulse-app.tls.certresolver=mytlschallenge" # ИСПРАВЛЕНО
      - "traefik.http.services.pulse-app.loadbalancer.server.port=3000"
    networks:
      - default
      - n8n_network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: pulse_password
      POSTGRES_DB: pulse_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

networks:
  default:
  n8n_network:
    external: true
    name: n8n_default

volumes:
  postgres_data:
